#!/bin/bash

OWNER=${1}
PARTNER_ALIAS=""
BOARD_ALIAS=""
ROOT_DIRECTORY=`pwd`
BASEROOT_SDK=${ROOT_DIRECTORY}/../../${OWNER}

STRING_INTERNET_ERROR="Impossible to connect to internet, double check your Internet connection."
STRING_ARGS_ERROR="Parameters used unknown"

#######################################################################################################################
# Error message

function error_message()
{
    local ZENITY_INSTALLED
    ZENITY_INSTALLED=`dpkg-query -l | grep zenity-common |& awk -F" " '{ print $1 }'`

    if [ "${ZENITY_INSTALLED}" != "ii" ]
    then
    echo "${1}"
    else
    zenity --error --text "${1}"
    fi
}

#######################################################################################################################
# Update splashscreen target board

if [ "${OWNER}" == "architech" ]
then
    BOARD_ALIAS=${2}    
    cd ${BASEROOT_SDK}/${BOARD_ALIAS}/splashscreen
elif [ "${OWNER}" == "partners" ]
then
    PARTNER_ALIAS=${2}
    BOARD_ALIAS=${3}
    cd ${BASEROOT_SDK}/${PARTNER_ALIAS}/${BOARD_ALIAS}/splashscreen
else
    error_message "${STRING_ARGS_ERROR}"
    exit 2
fi
git pull
[ $? -eq 0 ] || { error_message "${STRING_INTERNET_ERROR}"; exit 1; }

#######################################################################################################################
# Update target board

gnome-terminal --disable-factory -t ${BOARD_ALIAS} -e 'bash -c "./run_install"';

exit $?
