#!/bin/bash
[ $# -eq 1 ] || exit 1
SPLASH_SCREEN_DIRECTORY=$1
cd ${SPLASH_SCREEN_DIRECTORY}
sleep 2
git pull
UPDATE_RESULT=$?
gnome-terminal --disable-factory -t "*** Updating Splashscreen, please wait... ***" -e './scripts/install';
./splashscreen
exit ${UPDATE_RESULT}
